myblog/urls.py
"""myblog URL Configuration"""

from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from posts.admin import custom_admin_site

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', custom_admin_site.urls),
    path('', views.homepage, name='home'),
    path("posts/", include('posts.urls')),
    
    
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('<slug:slug>', views.post_page, name='page')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
   # later for login lougout
]

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=75)
  body = models.TextField()
  slug = models.SlugField()
  date = models.DateTimeField(auto_now_add=True)
  banner = models.ImageField(default='laptop_computer.jpg', blank=True)

  def __str__(self):
    return self.title

users/models.py
from django.db import models

# Create your models here.

myblog/views.py
'''
contains the logic that processes requests and returns responses.
It acts as an intermediary between models (data) and templates (presentation).
'''

from django.shortcuts import render
from posts.models import Post

def homepage(request):
  posts = Post.objects.all().order_by('-date')[:3]
  return render(request, 'index.html', {'posts': posts})

posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse

# Create your views here.
def posts_list(request):
  posts = Post.objects.all().order_by('-date')
  return render(request, 'posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
  post = Post.objects.get(slug=slug)
  return render(request, 'posts/post_page.html', {'post': post})

users/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
  {{post.title}}
{% endblock  %}


{% block content %}  
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
  <article class="text-center mt-20">
      <h2 class="text-3xl font-extrabold text-gray-900">{{post.title}}</h2>
      <h2 class=" mt-2 text-sm  text-gray-500">{{post.date | date:'M d, Y'}}</h2>
      <p class="mt-2" >
        <img src="{{post.banner.url}}" alt="{{post.title}}" >
        {{post.body}}
      </p>
      <p class="mt-4 text-lg text-black">{{post.body}}</p>
  </article>
  
</div>

{% endblock %}

posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
  Posts
{% endblock  %}


{% block content %}  

<!-- Section -->
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
  <div class="text-center">
      <h2 class="text-3xl font-extrabold text-gray-900">From the blog</h2>
      <p class="mt-2 text-lg text-gray-600">Learn how to grow your business with our expert advice.</p>
  </div>
  
  <div class="mt-12 grid gap-8 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
    {% for post in posts %}
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
          <img class="w-full h-96 object-cover" src="{{post.banner.url}}" alt="{{post.title}}">
          <div class="px-4 py-5 sm:p-6">
              <div class="text-xs text-gray-500 mb-2">{{post.date | date:'M d, Y'}}</div>
              <span class="inline-block bg-gray-200 text-gray-800 text-xs px-2 py-1 rounded-full uppercase font-semibold tracking-wide">{{post.slug}}</span>
              <h3 class="mt-4 text-xl font-semibold text-gray-900">
                <a href="{% url 'posts:page' slug=post.slug %}">
                  {{ post.title}}
                </a>
              </h3>
              <p class="mt-2 text-gray-500 text-sm">
                {{ post.body }}
              </p>
              
          </div>
      </div>
      {% endfor %}
  </div>
  
</div>

{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block title %}
  Home
{% endblock  %}


{% block content %}  
    <!-- Header -->
    
    <!-- Hero -->
    <div class="relative isolate px-6 pt-14 lg:px-8">
      <div class="absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80" aria-hidden="true">
        <div class="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-30rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
      </div>
      <div class="mx-auto max-w-2xl py-32 sm:py-48 lg:py-56">
        <div class="hidden sm:mb-8 sm:flex sm:justify-center">
          <div class="relative rounded-full px-3 py-1 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
            &#128075; Welcome to My Tech Blog Journey! <span role='img' arial-label='s'>✨</span>
          </div>
        </div>
        <div class="text-center">
          <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">Tech insights to power your digital future</h1>
          <p class="mt-6 text-lg leading-8 text-gray-600">Stay ahead of the curve with our in-depth analysis of emerging technologies, industry trends, and innovative solutions shaping the tech landscape.</p>
          <div class="mt-10 flex items-center justify-center gap-x-6">
            <a href="{% url 'posts:list' %}" class="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"><span role='img' arial-label='b'>📚</span> Read more</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-x-0 top-[calc(100%-13rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-30rem)]" aria-hidden="true">
        <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
      </div>
    </div>
  
    <!-- Section -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <div class="text-center">
        <h2 class="text-3xl font-extrabold text-gray-900">From the blog</h2>
        <p class="mt-2 text-lg text-gray-600">Learn how to grow your business with our expert advice.</p>
    </div>
    <div class="mt-12 grid gap-8 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
      {% for post in posts %}
      <div class="bg-white shadow overflow-hidden sm:rounded-lg">
          <img class="w-full h-96 object-cover" src="{{post.banner.url}}" alt="{{post.title}}">
          <div class="px-4 py-5 sm:p-6">
              <div class="text-xs text-gray-500 mb-2">{{post.date | date:'M d, Y'}}</div>
              <span class="inline-block bg-gray-200 text-gray-800 text-xs px-2 py-1 rounded-full uppercase font-semibold tracking-wide">{{post.slug}}</span>
              <h3 class="mt-4 text-xl font-semibold text-gray-900">
                <a href="{% url 'posts:page' slug=post.slug %}">
                  {{ post.title}}
                </a>
              </h3>
              <p class="mt-2 text-gray-500 text-sm">
                {{ post.body }}
              </p>
              
          </div>
      </div>
      {% endfor %}
    </div>
    </div>

{% endblock  %}

templates/layout.html
{% load compress %}
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}
      Dongyang &apos; Blog
    {% endblock  %}
  </title>
  
  {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
  {% endcompress %}
  <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body class="bg-gray-100 bg-[radial-gradient(circle,_#0a0a0a_0.5px,_transparent_0.8px)] bg-[size:20px_20px] ">
  <div >
    <header class="absolute inset-x-0 top-0 z-50">
      <nav class="flex items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
      <a href="{% url 'home' %}" class="-m-1.5 p-1.5">
        <span class="sr-only">My Blog</span>
        <img class="h-8 w-auto" src="{% static 'images/logo.svg' %}" alt="logo">
      </a>
    </div>
    
    <div class="lg:flex lg:flex-1 lg:justify-end">
      <a href="/admin" class="text-sm font-semibold leading-6 text-gray-900">
        <span role='img' arial-label='w'>✍️</span> Write <span aria-hidden="true">&rarr;</span></a>
    </div>
    </nav> 
  </header>
</div>

<!-- Content -->
  <main>
    {% block content %}
    
    {% endblock %}
  </main>
<!-- Footer -->
  <div class='footer-fixed lg:relative bg-gray-600 text-white w-full bottom-0  flex justify-center items-center sm:px-6 lg:mt-48' >
  <div class="px-5 text-xs uppercase ">Made with <span role='img' arial-label='h'>❤️ </span> By Dongyang</div>
  <div class="px-5 text-xs uppercase">no cookies<span role='img' arial-label='c'>🍪</span> just colors<span role='img' arial-label='p'>🎨</span> and code<span role='img' arial-label='l'>👩🏻‍💻</span></div>
  <div class="hidden sm:flex sm:justify-center text-sm">©  2024</div>
  </div>
</body>
</html>